apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-operations
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  - metrics.k8s.io
  - storage.k8s.io
  resources:
  - pods/log
  - pods/portforward
  - pods/exec
  - pods/attach
  - cronjobs
  - componentstatuses
  - daemonsets
  - deployments
  - deployments/scale
  - events
  - endpoints
  - ingress
  - ingresses
  - jobs
  - limitranges
  - nodes
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  - resourcequotas
  - replicasets
  - replicationcontrollers
  - serviceaccounts
  - services
  - state fulsets
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
