apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-operations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-operations
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: default
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: operations
