apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: cluster-viewonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewonly
subjects:
- kind: ServiceAccount
  name: read-service-account
  namespace: default
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: view_only
